In [102]:
from haversine import haversine


a = (37.000000, 127.000000)
b1 = (37.000100, 127.00000)
b2 = (37.001000, 127.000000)
b3 = (37.003600, 127.000000)
c1 = (37.000000, 127.004500)


d1 = haversine(a, b1, unit = 'm')
print(d1)
d2 = haversine(a, b2, unit = 'm')
print(d2)
d3 = haversine(a, b3, unit = 'm')
print(d3)
d4 = haversine(a, c1, unit = 'm')
print(d4)

11.119508023465771
111.19508023324306
400.30228884052383
399.61952823795093

In [121]:
import csv
import pandas as pd
import numpy as np

cctv = pd.read_csv('./grid/cctv_clear.csv', encoding='utf-8', dtype={'위도':np.float, '경도':np.float})
light = pd.read_csv('./grid/merge_extract_light.csv', encoding='utf-8')
bell = pd.read_csv('./grid/Seoul_Bell.csv')

In [122]:
print(cctv)
print(light)
print(bell)

      관리기관명  카메라대수         위도          경도                   지번주소  \
0      관악구청      1  37.475891  126.940686  서울특별시 관악구 신림동 1564-68
1      관악구청      1  37.475996  126.941038  서울특별시 관악구 신림동 1564-68
2      관악구청      1  37.475878  126.953585  서울특별시 관악구 봉천동 1606-11
3      관악구청      1  37.476140  126.953750  서울특별시 관악구 봉천동 1606-11
4      관악구청      1  37.476974  126.935571   서울특별시 관악구 신림동 408-57
...     ...    ...        ...         ...                    ...
26265  금천구청      1  37.469427  126.901555    서울특별시 금천구 독산동 196-8
26266  금천구청      1  37.470096  126.900133    서울특별시 금천구 독산동 284-4
26267  금천구청      1  37.482621  126.884455   서울특별시 금천구 가산동 602-71
26268  금천구청      1  37.473450  126.892127    서울특별시 금천구 가산동 235-3
26269  금천구청      1  37.477559  126.893453   서울특별시 금천구 가산동 146-29

                        도로명주소
0        서울특별시 관악구 쑥고개로2라길 25
1        서울특별시 관악구 쑥고개로2라길 31
2          서울특별시 관악구 관악로6길 43
3          서울특별시 관악구 관악로6길 50
4          서울특별시 관악구 신림로39길 5
...                       ...
26265   서울특별시 금천구 독산로75길 12-7
26266   서울특별시 금천구 시흥대로128길 34
26267     서울특별시 금천구 벚꽃로38길 35
26268      서울특별시 금천구 가산로5길 43
26269  서울특별시 금천구 남부순환로110길 31

[26270 rows x 6 columns]
            id        lat         lng                       addr  \
0       161566  37.694032  127.043063      서울특별시 도봉구 도봉제1동 381-4
1       161565  37.693857  127.042836      서울특별시 도봉구 도봉제1동 379-1
2       161564  37.693668  127.043142        서울특별시 도봉구 도봉제1동 380
3       161563  37.693626  127.042661        서울특별시 도봉구 도봉제1동 379
4       161562  37.693622  127.043505        서울특별시 도봉구 도봉제1동 381
...        ...        ...         ...                        ...
137876    4768  37.433952  126.906444  서울특별시 금천구 시흥동 974-9 월편 산쪽
137877   66576  35.873147  128.593374         서울특별시 강동구 성내2동 9-5
137878   66574  35.872146  128.593377         서울특별시 강동구 성내2동 9-5
137879   66575  35.871146  128.593381         서울특별시 강동구 성내2동 9-5
137880   66010  35.868348  128.590381      서울특별시 강동구 성내2동 112-72

                             street  num
0             서울특별시 도봉구 도봉제1동 381-4    1
1             서울특별시 도봉구 도봉제1동 379-1    1
2               서울특별시 도봉구 도봉제1동 380    1
3               서울특별시 도봉구 도봉제1동 379    1
4            서울특별시 도봉구 평화로15번길 9-25    2
...                             ...  ...
137876  서울특별시 금천구 시흥대로 53 월편 기아대교 밑    1
137877        서울특별시 강동구 천호대로 지하도 입구    1
137878        서울특별시 강동구 천호대로 지하도 입구    1
137879        서울특별시 강동구 천호대로 지하도 입구    1
137880            서울특별시 강동구 올림픽로58길    1

[137881 rows x 6 columns]
              위도          경도              소재지도로명주소                소재지지번주소
0      37.577102  127.070903    서울특별시 동대문구 장한로 191    서울특별시 동대문구 장안2동 300
1      37.566531  127.073474    서울특별시 동대문구 장안벚꽃로67    서울특별시 동대문구 장안1동 356
2      37.573023  127.038554    서울특별시 동대문구 천계천로563     서울특별시 동대문구 용두동34-1
3      37.578401  127.062758   서울특별시 동대문구 전농로16길97  서울특별시 동대문구 전농동 산32-20
4      37.583198  127.065476  서울특별시 동대문구 휘경동 산6-80   서울특별시 동대문구 휘경동 산6-80
...          ...         ...                   ...                    ...
13083  37.600059  126.929413  서울특별시 은평구 응암동 177-24   서울특별시 은평구 응암동 177-24
13084  37.609322  126.934233  서울특별시 은평구 녹번동 산 1-55   서울특별시 은평구 녹번동 산 1-55
13085  37.609361  126.908975    서울특별시 은평구 구산동 산 34     서울특별시 은평구 구산동 산 34
13086  37.630801  126.927836  서울특별시 은평구 진관동 163-22   서울특별시 은평구 진관동 163-22
13087  37.593080  126.913834   서울특별시 은평구 신사동 35-20    서울특별시 은평구 신사동 35-20

[13088 rows x 4 columns]

In [123]:
# Data Frame의 위도 경도값을 보고 arr의 알맞는 위치에 개수를 셈

def count(df, c1, c2):
    # 구하려고 하는 범위의 위도 경도 범위
    ub = 37.700393
    bb = 37.426793
    height = ub-bb
    h_n = int(round(height/0.003600,0))
    lb = 126.764095
    rb = 127.182595
    width = rb-lb
    w_n = int(round(width/0.004500, 0))
    # 각 구역의 개수를 저장할 DataFrame 생성. 0으로 초기화
    d = pd.DataFrame(0, index=np.arange(h_n+1), columns=np.arange(w_n+1))

    
    for i in df.index:
        # 구하고자 하는 범위 내에 있으면 진행
        lat = float(df.loc[i, c1])
        lng = float(df.loc[i, c2])
        if bb <= lat and lat <= ub:
            if lb <= lng and lng <= rb: 
                # 몇번째 그리드 내에 있는지 계산
                i1 = int((lat-bb)/0.003600)
                i2 = int((lng-lb)/0.004500)
                x = d.iloc[i1,i2]
                d.iat[i1, i2] = x+1
    return d

In [109]:
cctv_df = count(cctv, '위도', '경도')
print(cctv_df)
# cctv_df.to_csv("./cctv결과.csv", header=False, index=False)

    0   1   2   3   4   5   6   7   8   9   ...  84  85  86  87  88  89  90  \
0    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
1    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
2    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
3    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
4    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..
72   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
73   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
74   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
75   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
76   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0

    91  92  93
0    0   0   0
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
..  ..  ..  ..
72   0   0   0
73   0   0   0
74   0   0   0
75   0   0   0
76   0   0   0

[77 rows x 94 columns]

In [124]:
light_df = count(light, 'lat', 'lng')
print(light_df)
# light_df.to_csv("./보안등결과.csv", header=False, index=False)

    0   1   2   3   4   5   6   7   8   9   ...  84  85  86  87  88  89  90  \
0    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
1    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
2    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
3    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
4    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..
72   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
73   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
74   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
75   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
76   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0

    91  92  93
0    0   0   0
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
..  ..  ..  ..
72   0   0   0
73   0   0   0
74   0   0   0
75   0   0   0
76   0   0   0

[77 rows x 94 columns]

In [126]:
bell_df = count(bell, '위도', '경도')
print(bell_df)
# bell_df.to_csv("./안전벨결과.csv", header=False, index=False)

    0   1   2   3   4   5   6   7   8   9   ...  84  85  86  87  88  89  90  \
0    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
1    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
2    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
3    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
4    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..
72   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
73   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
74   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
75   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0
76   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0

    91  92  93
0    0   0   0
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
..  ..  ..  ..
72   0   0   0
73   0   0   0
74   0   0   0
75   0   0   0
76   0   0   0

[77 rows x 94 columns]